language: java
jdk: openjdk12
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: impurity-online-gateway
addons:
  sonarcloud:
    organization: "tmk2003-github"
    token:
      secure: "$SONAR_TOKEN"
before_install:
  - chmod +x gradlew
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - ./gradlew sonarqube